const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const menu=$('.menu-toggle'),nav=$('nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('active',open);menu.setAttribute('aria-expanded',String(open))});
$$('nav a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('active');menu.setAttribute('aria-expanded','false')}));
$('#year').textContent=new Date().getFullYear();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.1});
$$('.reveal').forEach(el=>revealObserver.observe(el));
const progressBar=$('#progressBar');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progressBar.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
const tabs=$$('.protocol-tab'),panels=$$('.protocol-panel');
tabs.forEach(tab=>tab.addEventListener('click',()=>{const step=tab.dataset.step;tabs.forEach(item=>{const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active))});panels.forEach(panel=>{const active=panel.dataset.panel===step;panel.classList.toggle('active',active);panel.hidden=!active})}));
const toast=$('.toast');$('.copy-trigger').addEventListener('click',async event=>{const text=event.currentTarget.dataset.copy;try{await navigator.clipboard.writeText(text);toast.textContent='PROMPT COPIED'}catch{toast.textContent='SELECT & COPY THE PROMPT'}toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)});
const finePointer=matchMedia('(pointer:fine)').matches;
if(finePointer){const aura=$('.cursor-aura'),core=$('.cursor-core');let trailTick=0;addEventListener('pointermove',event=>{aura.style.left=core.style.left=event.clientX+'px';aura.style.top=core.style.top=event.clientY+'px';if(++trailTick%4===0){const trail=document.createElement('i');trail.className='trail';trail.style.left=event.clientX+'px';trail.style.top=event.clientY+'px';document.body.appendChild(trail);trail.addEventListener('animationend',()=>trail.remove())}},{passive:true});$$('.tilt-card').forEach(card=>{card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;card.style.transform='perspective(900px) rotateX('+(y*-6)+'deg) rotateY('+(x*8)+'deg) translateY(-5px)'});card.addEventListener('pointerleave',()=>card.style.transform='')});const stage=$('.field-stage');stage.addEventListener('pointermove',event=>{const rect=stage.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;stage.style.transform='perspective(1000px) rotateX('+(y*-4)+'deg) rotateY('+(x*5)+'deg)'});stage.addEventListener('pointerleave',()=>stage.style.transform='')}
const canvas=$('#field'),ctx=canvas.getContext('2d');let width,height,ratio,particles=[],pointer={x:0,y:0,active:false},comets=[];
function resetField(){ratio=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(ratio,0,0,ratio,0,0);const count=Math.min(145,Math.floor(width/7));particles=Array.from({length:count},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.4+.35,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,a:Math.random()*.55+.2,phase:Math.random()*Math.PI*2}))}
function drawField(time){ctx.clearRect(0,0,width,height);particles.forEach((p,index)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=width;if(p.x>width)p.x=0;if(p.y<0)p.y=height;if(p.y>height)p.y=0;const pulse=.7+Math.sin(time/1100+p.phase)*.3;ctx.globalAlpha=p.a*pulse;ctx.fillStyle=index%5===0?'#72ecff':'#8068ff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();for(let j=index+1;j<particles.length;j++){const q=particles[j],dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d<90){ctx.globalAlpha=(1-d/90)*.07;ctx.strokeStyle='#7598ff';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}});if(pointer.active){const glow=ctx.createRadialGradient(pointer.x,pointer.y,0,pointer.x,pointer.y,170);glow.addColorStop(0,'rgba(114,236,255,.12)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.globalAlpha=1;ctx.fillStyle=glow;ctx.fillRect(pointer.x-170,pointer.y-170,340,340)}comets=comets.filter(c=>c.life>0);comets.forEach(c=>{c.x+=c.vx;c.y+=c.vy;c.life--;ctx.globalAlpha=c.life/c.max;ctx.strokeStyle='#72ecff';ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(c.x-c.vx*10,c.y-c.vy*10);ctx.stroke()});requestAnimationFrame(drawField)}
addEventListener('resize',resetField);addEventListener('pointermove',e=>pointer={x:e.clientX,y:e.clientY,active:true},{passive:true});addEventListener('wheel',e=>{if(!finePointer)return;for(let i=0;i<5;i++)comets.push({x:pointer.x+(Math.random()-.5)*90,y:pointer.y+(Math.random()-.5)*90,vx:(Math.random()-.5)*2,vy:(e.deltaY>0?1:-1)*(2+Math.random()*2),life:30,max:30})},{passive:true});resetField();if(!matchMedia('(prefers-reduced-motion:reduce)').matches)requestAnimationFrame(drawField);